### ISSUE TITLE
Prueba Fallida en Kraken de escenario 4 - Publicar Post Agendado

### ISSUE THREAD

**Issue by dfgoUniandes** [e-rativa/BDD-Semana-5#4]
Prueba Fallida en Kraken de escenario 4 - Publicar Post Agendado, Version Ghost 3.42.5
![PublicarPostAgendado_11_](https://user-images.githubusercontent.com/78925077/118348532-a35fc980-b510-11eb-9db8-07978ee7c68e.png)

**Comment by e-rativa** [comment]
Se realizaron cambios para corregir la prueba de kraken del escenario 11
