### ISSUE TITLE
Error escenario 5

### ISSUE THREAD

**Issue by OscarCortesMedina** [e-rativa/BDD-Semana-5#5]
Al no poder completar el escenario 4 el escenario 5 no se ejecuta, por consiguiente no se realizó la prueba. 
![PublicarPostAgendado_11_](https://user-images.githubusercontent.com/78661986/118348755-fb4b0000-b511-11eb-86f8-e2f33c291c5c.png)

**Comment by e-rativa** [comment]
Se corrigió el escenario 4, El escenario 5 funciona correctamente
